[colors.primary]
background = "#262626"
foreground = "#ABB2BF"
bright_foreground = "#FFFFFF"

[colors.cursor]
text = "#282C34"
cursor = "#ABB2BF"

[colors.vi_mode_cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.selection]
text = "CellForeground"
background = "#282C34"

[colors.normal]
black = "#262626"
red = "#E06C75"
green = "#98C379"
yellow = "#E5C07B"
blue = "#61AFEF"
magenta = "#C678DD"
cyan = "#56B6C2"
white = "#ABB2BF"

[colors.bright]
black = "#363636"
red = "#F07C85"
green = "#A8D389"
yellow = "#F5D08B"
blue = "#71BFFF"
magenta = "#D688ED"
cyan = "#66C6D2"
white = "#BBC2CF"
